- hosts: all
  gather_facts: false
  vars:
    workdir: /srv/owlcms/
  tasks:
  - name: Copy docker files
    copy:
      src: ansible/docker/
      dest: "{{ workdir }}"

  - name: Create .env
    template:
      src: ansible/files/.env
      dest: "{{ workdir }}/.env"