- hosts: all
  gather_facts: false
  vars:
    workdir: /srv/owlcms
  tasks:
  - name: Copy docker files
    copy:
      src: ../docker/
      dest: "{{ workdir }}/"

  - name: Create .env
    template:
      src: files/.env
      dest: "{{ workdir }}/.env"