- hosts: all
  gather_facts: false
  vars:
    workdir: /srv/owlcms
  tasks:
  - name: Copy docker files
    copy:
      src: ../docker/
      dest: "{{ workdir }}/"

  - name: Create docker .env file
    template:
      src: files/docker-env.j2
      dest: "{{ workdir }}/.env"

  - name: Deploy containers
    community.docker.docker_compose:
      project_src: "{{ workdir }}"
      files:
      - docker-compose.yml