name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker installation playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: setup-docker.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          directory: ansible
          inventory: ${{ secrets.INVENTORY }}
          options: |
            --extra-vars ${{ secrets.EXTRA_VARS }}